name: app_assurance

type: php:8.1

dependencies:
    php:
        composer/composer: "^2"

runtime:
    extensions:
        - apcu
        - blackfire
        - ctype
        - iconv
        - mbstring
        - sodium
        - xsl
        - calendar
        - imagick
        - intl
        - fileinfo

variables:
    env:
        APP_ENV: "prod"
        APP_DEBUG: 0
    php:
        memory_limit: "256M"
        post_max_size: 10M
        upload_max_filesize: 100M

build:
    flavor: "composer"

relationships:
    database: "mysqldb:mysql"

crons:
    security-check:
        spec: "50 23 * * *"

        cmd: if [ "$PLATFORM_BRANCH" = "main" ]; then croncape php-security-checker; fi

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | bash

        symfony-build

    deploy: |
        set -x -e

        symfony-deploy

disk: 2048 #2G

mounts:
    "/var/cache": "shared:files/cache"
    "/var/log": "shared:files/log"
    "/var/sessions": "shared:files/sessions"
    "/public": "shared:files/public"


web:
    locations:
        "/":
            # The app's public directory_relative to its root.
            root: "public"
            # A front controller to_determine how to handle requests.
            passthru: "/index.php"
        # Allow uploaded files to be served, but don't run scripts.
        # Missing files get sent to the front controller.
        "/files":
            root: "web/files"
            scripts: false
            allow: true
            passthru: "/index.php"
