name: app_assurance

type: php:8.2



variables:
    env:
        APP_ENV: "dev"
        APP_DEBUG: 0


relationships:
    database: "mysqldb:mysql"


disk: 2048 #2G

mounts:
    "/var/cache": "shared:files/cache"
    "/var/log": "shared:files/log"
    "/var/sessions": "shared:files/sessions"
    "/public": "shared:files/public"

web:
  locations:
    "/":
      root: "public"
      index: ["index.php"]
      scripts: true
      allow: true
      rules:
        '\.php$':
          allow: true
        '/':
          try_files: '$uri /index.php$is_args$args'
