name: app_assurance

type: php:8.2

variables:
  env:
    APP_ENV: prod
    APP_DEBUG: 0
    TRUSTED_PROXIES: '*'
    TRUSTED_HOSTS: '^.+$'


relationships:
    database: "mysqldb:mysql"


disk: 2048 #2G

mounts:
    "/var/cache": "shared:files/cache"
    "/var/log": "shared:files/log"
    "/var/sessions": "shared:files/sessions"
    "/public": "shared:files/public"

web:
  locations:
    /:
      root: public
      passthru: true
      index:
        - index.php
      allow: true
