name: app
type: php:8.2

variables:
  env:
    APP_ENV: dev
    APP_DEBUG: 1

relationships:
  database: mysqldb:mysql

disk: 2048

mounts:
    "/var/cache": "shared:files/cache"
    "/var/log": "shared:files/log"
    "/var/sessions": "shared:files/sessions"
    "/storage/app": "shared:files/storage-app"
    "/storage/framework": "shared:files/storage-framework"
    "/storage/logs": "shared:files/storage-logs"

hooks:
    build: |
        set -e
        mkdir -p storage/framework/{sessions,views,cache}
        mkdir -p storage/app/public
        mkdir -p bootstrap/cache
        chmod -R +w storage bootstrap/cache
    deploy: |
        set -e
        php artisan cache:clear
        mkdir -p storage/framework/{sessions,views,cache}
        mkdir -p storage/app/public
        chmod -R +w storage bootstrap/cache

web:
  locations:
    /:
      root: public
      passthru: /index.php
      index:
        - index.php
      allow: true
