# .platform.app.yaml
name: app
type: php:8.2

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      index:
        - index.php
      allow: true

mounts:
  "/public/uploads": "shared/uploads"
  "/storage": "shared/storage"

build:
  flavor: composer

dependencies:
  php:
    composer/composer: "^2.0"
