name: app
type: php:8.2

variables:
  env:
    APP_ENV: dev
    APP_DEBUG: 1

relationships:
  database: mysqldb:mysql

disk: 2048

mounts:
    # Chemins absolus corrigés pointant vers /var/www/html
    "/var/www/html/storage/framework/cache":
        source: local
        source_path: framework_cache
    "/var/www/html/storage/framework/sessions":
        source: local
        source_path: framework_sessions
    "/var/www/html/storage/framework/views":
        source: local
        source_path: framework_views
    "/var/www/html/storage/app/public":
        source: local
        source_path: storage_app
    "/var/www/html/bootstrap/cache":
        source: local
        source_path: bootstrap_cache

mounts:
    "/var/www/html/storage/framework/views":
        source: local
        source_path: framework_views
    "/var/www/html/bootstrap/cache":
        source: local
        source_path: bootstrap_cache

hooks:
    build: |
        set -ex
        mkdir -p storage/framework/{cache,sessions,views}
        mkdir -p bootstrap/cache
        chmod -R 775 storage bootstrap/cache
        [ ! -e public/storage ] && php artisan storage:link

    deploy: |
        set -ex
        # Réapplique les permissions
        chmod -R 775 storage/framework/views bootstrap/cache
        # Optimisations
        php artisan config:clear
        php artisan view:clear
        php artisan cache:clear
        php artisan config:cache
        php artisan view:cache

web:
  locations:
    /:
      root: public
      passthru: /index.php
      index:
        - index.php
      allow: true
