name: app
type: php:8.2

variables:
  env:
    APP_ENV: dev
    APP_DEBUG: 1

relationships:
  database: mysqldb:mysql

disk: 2048

mounts:
  "/var/cache": "shared:files/cache"
  "/var/log": "shared:files/log"
  "/var/sessions": "shared:files/sessions"
  # Retirez le montage /public qui cause probablement des problèmes

web:
  locations:
    /:
      root: public
      passthru: /index.php
      index:
        - index.php
      allow: true
