name: app
type: php:8.2

variables:
  env:
    APP_ENV: dev
    APP_DEBUG: 1

relationships:
  database: mysqldb:mysql

disk: 2048

mounts:
    # Chemins absolus corrigés pointant vers /var/www/html
    "/var/www/html/storage/framework/cache":
        source: local
        source_path: framework_cache
    "/var/www/html/storage/framework/sessions":
        source: local
        source_path: framework_sessions
    "/var/www/html/storage/framework/views":
        source: local
        source_path: framework_views
    "/var/www/html/storage/app/public":
        source: local
        source_path: storage_app
    "/var/www/html/bootstrap/cache":
        source: local
        source_path: bootstrap_cache

hooks:
    build: |
        set -ex
        # Création des dossiers locaux (dev)
        mkdir -p storage/framework/{cache,sessions,views}
        mkdir -p storage/app/public
        mkdir -p bootstrap/cache

        # Permissions
        chmod -R 775 storage bootstrap/cache
        chown -R $PLATFORM_APP_DIR:$PLATFORM_APP_DIR storage bootstrap/cache

        # Liens symboliques si nécessaire
        [ ! -e public/storage ] && php artisan storage:link

    deploy: |
        set -ex
        # Optimisations Laravel
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

        # Nettoyage
        php artisan cache:clear
        php artisan optimize

web:
  locations:
    /:
      root: public
      passthru: /index.php
      index:
        - index.php
      allow: true
