name: app
type: php:8.2

web:
  locations:
    "/":
      root: "public"
      index:
        - index.php
      scripts: true
      allow: true

mounts:
  "uploads":
    source: local
    source_path: uploads
  "storage":
    source: local
    source_path: storage

build:
  flavor: composer
