name: app_assurance

type: php:8.2

variables:
  env:
    APP_ENV: prod
    APP_DEBUG: 1  # Activez temporairement le débogage
    TRUSTED_PROXIES: '*'
    TRUSTED_HOSTS: '^.+$'
    APP_URL: https://{default}

relationships:
  database: "mysqldb:mysql"

disk: 2048

mounts:
  "/var/cache": "shared:files/cache"
  "/var/log": "shared:files/log"
  "/var/sessions": "shared:files/sessions"
  # Retirez le montage /public qui cause probablement des problèmes

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      index:
        - index.php
      # Ajoutez des règles pour servir les fichiers statiques
      rules:
        '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf|webp)$':
          allow: true
        '^/robots\.txt$':
          allow: true
