name: app_assurance
type: php:8.2

variables:
  env:
    APP_ENV: dev
    APP_DEBUG: 0

relationships:
  database: mysqldb:mysql

disk: 2048

mounts:
  /var/cache:
    source: local
    source_path: var/cache
  /var/log:
    source: local
    source_path: var/log
  /var/sessions:
    source: local
    source_path: var/sessions

web:
  locations:
    /:
      root: public
      passthru: /index.php
      index:
        - index.php
      allow: true
