services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: laravel
        uid: 1000
    image: mrseck/monassurance:v2
    container_name: monassurance-app
    restart: unless-stopped
    environment:
      - APP_NAME=MONASSURANCE V2
      - APP_ENV=local          
      - APP_KEY=base64:fO/IXUjokTcSSiJplLvtDAZZ1K3k0HS7O2n0MUVnJyY=
      - APP_DEBUG=false        
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SESSION_DRIVER=database
      - CACHE_DRIVER=file      
      - LOG_LEVEL=debug
    volumes:                   
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    networks:
      - monassurance

  db:
    image: mysql:8.0
    container_name: monassurance-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - monassurance

  nginx:
    image: nginx:1.25-alpine
    container_name: monassurance-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - monassurance
    depends_on:
      - app

networks:
  monassurance:
    driver: bridge

volumes:
  dbdata: