mysqldb:
    type: mysql:10.6
    disk: 2048 #2G 
    mounts:
        /var/lib/mysql:
            source: local
            source_path: var/lib/mysql
    configuration:
        mysql:
            max_connections: 1000
            max_allowed_packet: 16M
            wait_timeout: 28800
            interactive_timeout: 28800
